#!/usr/bin/env node
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function run(cmd, opts = {}){
  console.log('>', cmd);
  return execSync(cmd, { stdio: 'inherit', ...opts });
}

const repoRoot = path.resolve(__dirname, '..');
const functionsDir = path.join(repoRoot, 'functions');
const sharedDir = path.join(repoRoot, 'shared');

if (!fs.existsSync(functionsDir)) {
  console.error('functions directory not found');
  process.exit(1);
}

if (!fs.existsSync(sharedDir)) {
  console.error('shared directory not found');
  process.exit(1);
}

const pkgPath = path.join(functionsDir, 'package.json');
const pkgBackupPath = path.join(functionsDir, 'package.json.bak');

try {
  // Backup package.json
  fs.copyFileSync(pkgPath, pkgBackupPath);

  // Pack shared into functions dir (creates tarball in functions)
  console.log('Packing shared into functions directory...');
  run('npm pack ../shared', { cwd: functionsDir });

  // Find created tarball name
  const files = fs.readdirSync(functionsDir);
  const tgz = files.find(f => f.endsWith('.tgz') && f.includes('shared'));
  if (!tgz) {
    throw new Error('Packed shared .tgz not found in functions directory');
  }

  // Update functions/package.json to use file:./<tgz>
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.dependencies = pkg.dependencies || {};
  // Save original dependency value if exists
  const originalDep = pkg.dependencies['shared'];
  pkg.dependencies['shared'] = `file:./${tgz}`;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

  // Install functions deps (will install tarball as dependency)
  console.log('Installing functions dependencies...');
  run('npm install --no-audit --no-fund', { cwd: functionsDir });

  // Deploy functions
  console.log('Deploying functions...');
  run('firebase deploy --only functions', { cwd: repoRoot });

  console.log('\nDeployment completed.');

  // Restore original package.json
  console.log('Restoring original functions/package.json');
  fs.copyFileSync(pkgBackupPath, pkgPath);

  // Clean up tarball and node_modules generated by pack/install
  try {
    fs.unlinkSync(path.join(functionsDir, tgz));
  } catch (e) {}

  console.log('Restoring dependencies to original state...');
  run('npm install --no-audit --no-fund', { cwd: functionsDir });

  // Remove backup
  fs.unlinkSync(pkgBackupPath);
  console.log('Done.');

} catch (err) {
  console.error('Error during deploy script:', err);
  // Attempt to restore
  try {
    if (fs.existsSync(pkgBackupPath)) fs.copyFileSync(pkgBackupPath, pkgPath);
  } catch (e) {}
  process.exit(1);
}
